const PREFIX = "SEE_ALL/";

export const SHOW_COMPLETED_NOVELS_ONLY = PREFIX + "SHOW_COMPLETED_NOVELS_ONLY";
export const HIDE_COMPLETED_NOVELS_ONLY = PREFIX + "HIDE_COMPLETED_NOVELS_ONLY";
export const TOGGLE_COMPLETED_NOVELS_ONLY = PREFIX + "TOGGLE_COMPLETED_NOVELS_ONLY";

export const SELECT_CATEGORY = PREFIX + "SELECT_CATEGORY";
export const SELECT_TAG = PREFIX + "SELECT_TAG";
