const PREFIX = "SEE_ALL/";

export const SHOW_COMPLETED_NOVELS_ONLY = PREFIX + "SHOW_COMPLETED_NOVELS_ONLY";
export const HIDE_COMPLETED_NOVELS_ONLY = PREFIX + "HIDE_COMPLETED_NOVELS_ONLY";
export const TOGGLE_COMPLETED_NOVELS_ONLY = PREFIX + "TOGGLE_COMPLETED_NOVELS_ONLY";

export const SELECT_GENRE = PREFIX + "SELECT_GENRE";
export const SELECT_TYPE = PREFIX + "SELECT_TYPE";

export const SEARCH_NOVELS = PREFIX + "SEARCH_NOVELS";
export const SEARCH_NOVELS_FAIL = PREFIX + "SEARCH_NOVELS_FAIL";
export const SEARCH_NOVELS_SUCCESS = PREFIX + "SEARCH_NOVELS_SUCCESS";

export const START_LOADING_NOVELS = PREFIX + "START_LOADING_NOVELS";
export const STOP_LOADING_NOVELS = PREFIX + "STOP_LOADING_NOVELS";

export const SEARCH_APPEND_NOVELS = PREFIX + "SEARCH_APPEND_NOVELS";
export const SEARCH_APPEND_NOVELS_FAIL = PREFIX + "SEARCH_APPEND_NOVELS_FAIL";
export const SEARCH_APPEND_NOVELS_SUCCESS = PREFIX + "SEARCH_APPEND_NOVELS_SUCCESS";

export const START_LOADING_APPEND_NOVELS = PREFIX + "START_LOADING_APPEND_NOVELS";
export const STOP_LOADING_APPEND_NOVELS = PREFIX + "STOP_LOADING_APPEND_NOVELS";