const PREFIX = "HOME_TAB/";

export const GET_LASTEST_RELEASE_NOVELS = PREFIX + "GET_LASTEST_RELEASE_NOVELS";
export const GET_LASTEST_RELEASE_NOVELS_SUCCESS = PREFIX + "GET_LASTEST_RELEASE_NOVELS_SUCCESS";
export const GET_LASTEST_RELEASE_NOVELS_FAIL = PREFIX + "GET_LASTEST_RELEASE_NOVELS_FAIL";

export const GET_POPULAR_NOVELS = PREFIX + "GET_POPULAR_NOVELS";
export const GET_POPULAR_NOVELS_SUCCESS = PREFIX + "GET_POPULAR_NOVELS_SUCCESS";
export const GET_POPULAR_NOVELS_FAIL = PREFIX + "GET_POPULAR_NOVELS_FAIL";

export const SEARCH_KEYWORD_CHANGE = PREFIX + "SEARCH_KEYWORD_CHANGE";
