import { createAction } from './index';

const PREFIX = "HOME_TAB/";

export const GET_LASTEST_RELEASE_NOVELS = PREFIX + "GET_LASTEST_RELEASE_NOVELS";
export const GET_LASTEST_RELEASE_NOVELS_SUCCESS = PREFIX + "GET_LASTEST_RELEASE_NOVELS_SUCCESS";
export const GET_LASTEST_RELEASE_NOVELS_FAIL = PREFIX + "GET_LASTEST_RELEASE_NOVELS_FAIL";

export const GET_POPULAR_NOVELS = PREFIX + "GET_POPULAR_NOVELS";
export const GET_POPULAR_NOVELS_SUCCESS = PREFIX + "GET_POPULAR_NOVELS_SUCCESS";
export const GET_POPULAR_NOVELS_FAIL = PREFIX + "GET_POPULAR_NOVELS_FAIL";

export const GET_NEW_NOVEL = createAction(PREFIX + "GET_NEW_NOVEL");
export const GET_COMPLETE_NOVEL = createAction(PREFIX + "GET_COMPLETE_NOVEL");
export const GET_HOT_LIST_NOVEL = createAction(PREFIX + "GET_HOT_LIST_NOVEL");

export const GET_NEW_NOVEL_SUCCESS = PREFIX
export const SEARCH_KEYWORD_CHANGE = PREFIX + "SEARCH_KEYWORD_CHANGE";
