const PREFIX = "HOMETAB/";

export const GET_LASTEST_RELEASE = PREFIX + "GET_LASTEST_RELEASE";
export const GET_LASTEST_RELEASE_SUCCESS = PREFIX + "GET_LASTEST_RELEASE_SUCCESS";
export const GET_LASTEST_RELEASE_FAIL = PREFIX + "GET_LASTEST_RELEASE_FAIL";

export const SEARCH_KEYWORD_CHANGE = PREFIX + "SEARCH_KEYWORD_CHANGE";
