const PREFIX = "LIBRARY_TAB/";

export const GET_RECOMMEND_NOVELS = PREFIX + "GET_RECOMMEND_NOVELS";
export const GET_RECOMMEND_NOVELS_SUCCESS = PREFIX + "GET_RECOMMEND_NOVELS_SUCCESS";
export const GET_RECOMMEND_NOVELS_FAIL = PREFIX + "GET_RECOMMEND_NOVELS_FAIL";

export const SEARCH_KEYWORD_CHANGE = PREFIX + "SEARCH_KEYWORD_CHANGE";
